### ISSUE TITLE
Balance tweaks.

### ISSUE THREAD

**Issue by ZzZDracoZzZ** [breakinblocks/nutsandboltstorqued#126]
## **This is a collection of things that i think they need a tweak for balance purposes:**

**Magnetic Forcefield (The grapling hook mod)**
- Enables hyperfast flight requiring 8 iron ingots

**Acceleration Wand (Not Enough Wands)**
- If used with mechanical users, it can be stacked with itself, breaking time-space continuum generating millions of rf a tick at the cost of 3 bonemeal , 2 nether stars and 2 diamonds.

**Coal Generator (LibVulpes)**
- Generates an absurd 60k+ rf with a single piece of coal at the cost of 6 tin and 2 redstone, rendering other coal generators useless.

**Canister (Pressure Pipes)**
- Its expensive recipe defies his purpose, specially since you can just make a hundred-times-more-easier-to-do portable tank (Mekanism)

**Translocator/Transfer pipes (Extra Utilities 2)**
- Same as above, translocator's complex recipe renders his "quick transport fix" purpose useless, specially since you can just make a full stack of Transfer Pipes with 6 stone and 1 redstone dust.

**Experience Rod (EnderIO)**
- Vastly superior to other experience storagers, like the Tome of Peritia (Blood Magic) only requiring 2 soulsand, 2 glowstone, 2 redstone and 4 gold.

**EU:RF Conversion (Mekanism Cubes/Industrial Wires)**
- The conversion needs a nerf IMO to a lower RF output. A single piece of coal on a IC2 generator yields twice the RF than a stirling generator/furnace generator. The issue below is one of the consequences of this

**Nuclear Reactor (IC2) / Extreme Reactors**
- Nuclear Reactor is several times more efficient and powerfull than a extreme reactor can be thanks to EU:RF conversion, even though you need a IC2 reactor in order to craft a Reactor Controller.

**Fusion Reactor (Mekanism)**
- Even though Fusion reactor produces the triple more RF as a Draconic Evolution reactor, its way cheaper, rendering this last one useless.

Also no celestial manipulator recipe even in end-game :( (pleaserino?)

**Comment by Saereth** [comment]
1) I agree on the magnetic force, will add an appropriate recipe.

2) The libvulpes generator is new, didnt catch it in the udpate, it will be removed

3) Acceleration wand is meant be blacklisted from fakeplayers, will take care of that.
I will re-evaluate the canister recipe 

4) translocationors are much faster than standard exu transfer nodes, I will probably end up making exu pipes more expensive and translocators a little less expensive to find a middle ground here

5) experience rod recipe could probably use a revamp yeah, most likely will include xp shards from a woot factory

6) The reason a piece of coal yeilds so much more is ic2 generators are intentionally buffed, not a consequence of this. Ic2 generators are meant to be the early game power source. For those people that refuse to deal with ic2 subcrafting they can use a furnace/survivalist generator at lower power output. 

7) The easier mek cube recipe is an intentional way to allow for a semi unified power source early game. It doesn't bypass Ic2's power net, you must still apply the correct voltages and use transformers or it will blow up your ic2 machines. You'll notice the universal cables (except for ultimate tier) are disabled, so they are forced to use cubes and ic2 wiring. Ultimate tier require uumatter from top tier IC2 machines to produce, so you can use them eventually, but only after you've gotten your ic2 infrastrucutre rolling.

8) Ic2 reactor is even more powerful than baseline, nuclear fuel has been increased. You're assumption about it being better than extreme reactors is flawed however. Extreme reactors does not produce RF at all, passive generation is disabled. You can only produce steam with it, and its steam output has been increased significantly. When used with a mekanism turbine it can quite easily produce upwards up a million rf/t without even a single huge turbine.

9) The dragonic reactor is not a balancing point for this pack atm, it was recently added back and the recipes are default, more or less it's there for people that just want to experiment with it. There are no useful configuration options for me to tweak it to fit it better within the pack's progression right now, 
The fusion reactor is pretty much top tier power as it requires all previous power infrastructure to get there and by the time you can make a fusion reactor you could essentially make the creative items anyway. I suppose I could add some awakened draconium or something into the fusion recipes, any ideas for that?

10) Celestial manipulator recipe should definitely be there, I will double check that!

**Comment by ZzZDracoZzZ** [comment]
@Saereth Weird , i writed the big reactors issue because i was allowed to produce RF from passive generation, is it a bug, maybe?

![2017-04-10_15 59 11](https://cloud.githubusercontent.com/assets/27167914/24865159/bca2dd10-1e06-11e7-8cd3-21aa64e5acff.png)

**Comment by Saereth** [comment]
The power tap shouldnt have a recipe to craft it

**Comment by Saereth** [comment]
ok all these changes are done now for next update except translocatiors and item pipes, I'll give that a bit more thought as to how to best handle it, probably cheaper but require some kind of machine processing.

as for the canisters, they hold 64 buckets and act as a bucket as well, they are very good for what they do. so early game they are a bit pricey yes, but once you have some infrastructure their cost is trivial and they are very good. If I made them pre steel you'd be able to easily just take one to the nether, fill up and not worry about lava probably ever again. bucketing into portable tanks is at least a bit more work. 

We're testing these recipe changes on the test server and you should expect to see them in the next update.

**Comment by ZzZDracoZzZ** [comment]
@Saereth the problem isnt that they are not good enough, the problem is that mekanism tanks doubles as a bucket, essentially overriding the canisters at a much cheaper price, there is no work in filling the tanks since you can just right click as you do with the canisters :p

**Comment by Saereth** [comment]
ah they do that lol, ok mek tanks getting nerfed a bit, probably will require steel as well :p there is still the ender io tank for a cheap early game tank as well.

**Comment by Saereth** [comment]
All these are in the new update coming out later today
