### ISSUE TITLE
 2fps @ 50% CPU usage

### ISSUE THREAD

**Issue by implayin** [breakinblocks/nutsandboltstorqued#131]
Launcher Type MultiMC

Modpack version 1.6.4.5

Link to log file http://paste.feed-the-beast.com/view/da68a0a2

 I can only get between 1 and 4 fps while playing this pack.
According to task manager, I have about 50% CPU utilization and 60% RAM usage (4GB assigned to MC) (windows is in high-performance mode)
According to F3, the game uses my dedicated GPU.
I have no issues running other large modpacks like Beyond either.

**Comment by Doomgull** [comment]
How long did you let it go after first starting up this new world? It looks like about 2 minutes from the log, and it was still processing things back to the client thread. Was it also generating a new world? Looks like your client finally finished running texture generation and JEI changes and 30 seconds later you exited.

This is a pretty hefty pack, and has far more going on behind the scenes than even Beyond because of the number of custom recipes and tweaks.

Try reloading and letting it sit for a couple more minutes on first world-gen and load in of the client.

**Comment by Saereth** [comment]
Also turn your mipmaps off. This is an issue alot of people experience with betterFPS

**Comment by implayin** [comment]
mipmaps were the issue, thanks
